# Generated by Django 3.2.5 on 2021-07-08 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('payed_on', models.DateTimeField(auto_now=True)),
                ('subscribed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
