# Generated by Django 3.2.5 on 2021-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdetail_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=50),
        ),
    ]
