# Generated by Django 3.0.8 on 2021-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210831_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
